### ISSUE TITLE
🧰 - Sourcecred Set Up (yarn start)

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#91]
### General Issue

I'm good with all previous steps but ran into this error after `sudo yarn start`
```
yarn run v1.22.19
$ dotenv -- sourcecred go --no-load && sourcecred serve
  GO   graph
  GO   reference detector for sourcecred/discourse
 DONE  reference detector for sourcecred/discourse: 5ms
  GO   generating graph for sourcecred/discourse
 DONE  generating graph for sourcecred/discourse: 17ms
  GO   writing files
 DONE  writing files: 36ms
 DONE  graph: 66ms
  GO   contributions
  GO   writing files
 DONE  writing files: 1ms
 DONE  contributions: 2ms
  GO   hybrid
  GO   hybrid: running credrank
File not found at path: config/pluginBudgets.json. Defaulting.
 DONE  hybrid: running credrank: 104ms
  GO   hybrid: running credequate
 DONE  hybrid: running credequate: 0ms
  GO   hybrid: generating CredGrainView
 DONE  hybrid: generating CredGrainView: 10ms


# CredRank Scores
## Top Participants By Cred

| Description | Cred | % |
| --- | --- | --- |
| beanow-sc-test | 350.4 | 79.6% |
| d11 | 51.0 | 11.6% |
| dl-proto | 21.2 | 4.8% |
| system | 17.5 | 4.0% |
| SourceCred | 0.0 | 0.0% |
  GO   hybrid: writing changes
 DONE  hybrid: writing changes: 54ms
 DONE  hybrid: 170ms
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::6006
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.listen (/Users/twan/Github/template-instance/node_modules/express/lib/application.js:618:24)
    at serveCommand (webpack:///./src/cli/serve.js?:12:287)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 6006
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by twan-dev** [comment]
Tried `yarn clean` and `yarn clean-all` with no luck, then realized I was loading from the wrong site

**Comment by twan-dev** [comment]
solved. up and running.
